# Generated by Django 2.1 on 2018-09-30 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('faixa', models.CharField(choices=[('BRANCA', 'Branca'), ('CINZA', 'Cinza'), ('AMARELA', 'Amarela'), ('LARANJA', 'Laranja'), ('VERDE', 'Verde'), ('AZUL', 'Azul'), ('ROXA', 'Roxa'), ('MARROM', 'Marrom'), ('PRETA', 'Preta')], max_length=100, verbose_name='Graduação')),
                ('datagraduacao', models.DateTimeField(verbose_name='Data Graduação')),
                ('datanascimento', models.DateTimeField(verbose_name='Data Nascimento')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('ENCERRADO', 'Encerrado'), ('TRANCADO', 'Trancado')], max_length=100, verbose_name='Status Aluno')),
                ('observacao', models.CharField(max_length=100, verbose_name='Observação')),
            ],
        ),
        migrations.CreateModel(
            name='Mensalidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(choices=[('JANEIRO', 'Janeiro'), ('FEVEREIRO', 'Fevereiro'), ('MARÇO', 'Março'), ('ABRIL', 'Abril'), ('MAIO', 'Maio'), ('JUNHO', 'Junho'), ('JULHO', 'Julho'), ('AGOSTO', 'Agosto'), ('SETEMBRO', 'Setembro'), ('OUTUBRO', 'Outubro'), ('NOVEMBRO', 'Novembro'), ('DEZEMBRO', 'Dezembro')], max_length=100, verbose_name='Mês')),
                ('dataPagamento', models.DateTimeField(verbose_name='Data de Pagamento')),
                ('valorPago', models.CharField(max_length=20, verbose_name='Valor Pago')),
                ('categoria', models.CharField(choices=[('CRIANCA', 'Crianca'), ('ADULTO', 'Adulto')], max_length=100, verbose_name='Categoria')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Aluno', verbose_name='Aluno')),
            ],
        ),
    ]
