# Generated by Django 2.1 on 2018-10-13 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagar', models.CharField(choices=[('LUZ', 'Luz'), ('AGUA', 'Agua'), ('TELEFONE', 'Telefone'), ('CARRO', 'Carro'), ('NET', 'Net'), ('NU', 'Nu'), ('KITNET', 'Kitnet')], max_length=100, verbose_name='Contas')),
                ('categoria', models.CharField(choices=[('PESSOAL', 'Pessoal'), ('ACADEMIA', 'Academia')], max_length=100, verbose_name='Categoria')),
                ('mes', models.CharField(choices=[('JANEIRO', 'Janeiro'), ('FEVEREIRO', 'Fevereiro'), ('MARÇO', 'Março'), ('ABRIL', 'Abril'), ('MAIO', 'Maio'), ('JUNHO', 'Junho'), ('JULHO', 'Julho'), ('AGOSTO', 'Agosto'), ('SETEMBRO', 'Setembro'), ('OUTUBRO', 'Outubro'), ('NOVEMBRO', 'Novembro'), ('DEZEMBRO', 'Dezembro')], max_length=100, verbose_name='Mês')),
                ('dataPagamento', models.DateTimeField(verbose_name='Data de Pagamento')),
                ('valorPago', models.CharField(max_length=20, verbose_name='Valor Pago')),
            ],
        ),
    ]
